language: rust
sudo: false
cache: cargo
rust:
- stable
- beta
- nightly
before_script:
- export PATH="$PATH:$HOME/.cargo/bin"
script:
- cargo build --verbose
- cargo test --verbose
- cargo run --example cmd-program
- cargo run --example cmd-program -- --verbose
